// utils/export/print.ts
// import { Data } from "@/components/DriverManagement";

type DataTypes = {
    id: number;
    lastName: string | null;
    firstName: string | null;
    address?: string | null;
    gender?: string | null;
    status: string;
    driverId?: string;
    userId?: string;
}

export const printTable = (data: DataTypes[], options?: { title?: string; logoUrl?: string }) => {
  const { title = "Users Report", logoUrl } = options || {};

  const currentDate = new Date().toLocaleString();

  const htmlContent = `
    <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
            color: #333;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
          }
          .logo {
            max-height: 50px;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #888;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th, td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
          }
          th {
            background-color: #f0f0f0;
          }
        </style>
      </head>
      <body>
        <div class="header">
          ${logoUrl ? `<img src="${logoUrl}" class="logo" />` : ""}
          <div>
            <h2>${title}</h2>
            <p>${currentDate}</p>
          </div>
        </div>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Full Name</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>
                <td>${row.id}</td>
                <td>${row.firstName}</td>
                <td>${row.lastName}</td>
                <td>${row.gender}</td>
                <td>${row.status}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">
          <p>Generated by MyApp | &copy; ${new Date().getFullYear()}</p>
        </div>
      </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  }
};
